spring:
  datasource:
    url: jdbc:mysql://database-1.czu06i00m58j.ap-northeast-2.rds.amazonaws.com:3306/wuzu
    username: admin
    password: sharon11
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
